blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [

    path('', BlogView.as_view(), name='blog'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/', cache_page(60)(BlogDetailView.as_view()), name='blog_article', ),
    path('update/<slug:slug>/', BlogUpdateView.as_view(), name='blog_update', ),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete', ),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail_sender.urls', namespace='mailsender')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail_sender/urls.py
from django.urls import path

from mail_sender import views as my_view
from mail_sender.apps import MailSenderConfig

app_name = MailSenderConfig.name

urlpatterns = [

    path('', my_view.home, name='home'),

    path('customers', my_view.CustomersView.as_view(), name='all_customers'),
    path('customer/<int:pk>', my_view.CustomerDetailView.as_view(), name='customer'),
    path('customer/create', my_view.CustomerCreateView.as_view(), name='customer_create'),
    path('customer/update/<int:pk>', my_view.CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/delete/<int:pk>', my_view.CustomerDeleteView.as_view(), name='customer_delete'),

    path('email-templates', my_view.ContentEmailView.as_view(), name='all_email_templates'),
    path('email-template/<int:pk>', my_view.ContentEmailDetailView.as_view(), name='email_template'),
    path('email-template/create', my_view.ContentEmailCreateView.as_view(), name='email_template_create'),
    path('email-template/update/<int:pk>', my_view.ContentEmailUpdateView.as_view(), name='email_template_update'),
    path('email-template/delete/<int:pk>', my_view.ContentEmailDeleteView.as_view(), name='email_template_delete'),

    path('email-settings', my_view.SetEmailingView.as_view(), name='all_emailing'),
    path('email-setting/<int:pk>', my_view.SetEmailingDetailView.as_view(), name='email_setting'),
    path('email-setting/create', my_view.SetEmailingCreateView.as_view(), name='email_setting_create'),
    path('email-setting/update/<int:pk>', my_view.SetEmailingUpdateView.as_view(), name='email_setting_update'),
    path('email-setting/delete/<int:pk>', my_view.SetEmailingDeleteView.as_view(), name='email_setting_delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, wait_confirm_email, ConfirmPage, UserForgotPasswordView, \
     UserPasswordResetDoneView, UserPasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('wait-confirm-email/', wait_confirm_email, name='confirm_email'),
    path('confirm_email/<int:pk>', ConfirmPage.as_view(), name='confirmed_email'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-sent/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

mail_sender/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}

CHOICES_STATUS = (
    ('CR', 'Created'),
    ('IP', 'In Progress'),
    ('CL', 'Closed'),
)

FREQUENCY_SEND = (
    ('OD', 'Once a day'),
    ('OW', 'Once a week'),
    ('OM', 'Once a month'),
)

# TIME_SEND = (
#     ('00:00', '00:00:00'),
#     ('08:00', '08:00:00'),
#     ('10:00', '10:00:00'),
#     ('12:00', '12:00:00'),
#     ('14:00', '14:00:00'),
#     ('16:00', '16:00:00'),
# )


class Customer(models.Model):
    email = models.CharField(max_length=150, verbose_name='e-mail')
    full_name = models.CharField(max_length=150, verbose_name='фио', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    is_blocked = models.BooleanField(default=False, verbose_name='заблокирован')

    def delete(self, *args, **kwargs):
        self.is_blocked = True
        self.save()

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'получатель'
        verbose_name_plural = 'получатели'


class ContentEmail(models.Model):
    headliner = models.CharField(max_length=150, verbose_name='тема письма')
    text = models.TextField(verbose_name='текст письма')
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Добавлено', **NULLABLE)

    def __str__(self):
        return f'{self.headliner}'

    class Meta:
        verbose_name = 'письмо для рассылки'
        verbose_name_plural = 'письма для рассылки'


class SendSettings(models.Model):

    name = models.CharField(max_length=150, verbose_name='название рассылки')
    send_time = models.TimeField(verbose_name='Время отправки')
    period = models.CharField(max_length=2, choices=FREQUENCY_SEND, default='OM', verbose_name='Частота рассылки')
    status = models.CharField(max_length=2, choices=CHOICES_STATUS, default='CR', verbose_name='Статус')
    message = models.ForeignKey(ContentEmail, on_delete=models.CASCADE, verbose_name='Текст рассылки', **NULLABLE)
    customer = models.ManyToManyField(Customer, verbose_name='Клиенты', **NULLABLE)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Добавлено', **NULLABLE)

    def delete(self, *args, **kwargs):
        self.status = 'CL'
        self.save()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'настройка рассылки'
        verbose_name_plural = 'настройки рассылок'


class EmailLogs(models.Model):
    data_last_sent = models.DateTimeField(verbose_name='дата последней рассылки')
    status_issue = models.BooleanField(default=False, verbose_name='статус попытки')
    server_respond = models.CharField(max_length=50, verbose_name='ответ сервера', **NULLABLE)
    sender = models.ForeignKey(SendSettings, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.server_respond}'

mail_sender/forms.py
from django import forms
from mail_sender.models import Customer, ContentEmail, SendSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class CustomerForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Customer
        fields = '__all__'


class WriteEmailForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = ContentEmail
        exclude = ('created_by',)


class SendSettingsForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = SendSettings
        exclude = ('status', 'created_by',)

mail_sender/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from mail_sender import models as my_models
from mail_sender import forms as my_forms
from blog.models import Blog
from mail_sender.services import get_cache


def home(request):
    customers = my_models.Customer.objects.all()
    settings = my_models.SendSettings.objects.all()
    act_settings = my_models.SendSettings.objects.filter(status='CR')
    blog_posts = Blog.objects.filter(is_published=True)
    blog_posts_random = blog_posts.order_by('?')[:3]
    context = {
        'customers': customers,
        'settings': settings,
        'act_settings': act_settings,
        'blog_posts': blog_posts,
        'blog_posts_random': get_cache('posts', blog_posts_random),
        'title': 'Главная'
    }
    return render(request, 'mail_sender/home.html', context)


class CheckPermEditMixin:
    """Mixin для проверки владельца или суперпользователя"""
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request.user and not self.request.user.is_superuser:
            raise Http404('Недостаточно прав доступа - только владелец может редактировать эту страницу')
        return self.object


class CustomersView(LoginRequiredMixin, generic.ListView):
    model = my_models.Customer
    extra_context = {
        'title': 'Получатели'
    }

    def get_queryset(self, *args, **kwargs):
        """выборка активных пользователей из всех"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_blocked=False)
        return queryset


class CustomerDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.Customer

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class CustomerCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.Customer
    form_class = my_forms.CustomerForm
    success_url = reverse_lazy('mailsender:all_customers')


class CustomerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = my_models.Customer
    form_class = my_forms.CustomerForm
    success_url = reverse_lazy('mailsender:all_customers')


class CustomerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.Customer
    success_url = reverse_lazy('mailsender:all_customers')
    extra_context = {
        'title': 'Удалить получателя'
    }


class ContentEmailView(LoginRequiredMixin, generic.ListView):
    model = my_models.ContentEmail
    extra_context = {
        'title': 'Шаблоны писем'
    }


class ContentEmailDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.ContentEmail

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ContentEmailCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.ContentEmail
    form_class = my_forms.WriteEmailForm
    success_url = reverse_lazy('mailsender:all_email_templates')

    def form_valid(self, form):
        """заполнение поля владельца при валидации формы"""
        if form.is_valid():
            fields = form.save(commit=False)
            fields.created_by = self.request.user
        return super().form_valid(form)


class ContentEmailUpdateView(LoginRequiredMixin, CheckPermEditMixin, generic.UpdateView):
    model = my_models.ContentEmail
    form_class = my_forms.WriteEmailForm
    success_url = reverse_lazy('mailsender:all_email_templates')


class ContentEmailDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.ContentEmail
    success_url = reverse_lazy('mailsender:all_email_templates')
    extra_context = {
        'title': 'Удалить шаблон письма'
    }


class SetEmailingView(LoginRequiredMixin, generic.ListView):
    model = my_models.SendSettings
    extra_context = {
        'title': 'Настройки рассылок'
    }


class SetEmailingDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.SendSettings

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class SetEmailingCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.SendSettings
    form_class = my_forms.SendSettingsForm
    success_url = reverse_lazy('mailsender:all_emailing')

    def form_valid(self, form):
        """заполнение поля владельца при валидации формы"""
        if form.is_valid():
            fields = form.save(commit=False)
            fields.created_by = self.request.user
        return super().form_valid(form)


class SetEmailingUpdateView(LoginRequiredMixin, CheckPermEditMixin, generic.UpdateView):
    model = my_models.SendSettings
    form_class = my_forms.SendSettingsForm
    success_url = reverse_lazy('mailsender:all_emailing')


class SetEmailingDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.SendSettings
    success_url = reverse_lazy('mailsender:all_emailing')
    extra_context = {
        'title': 'Удалить настройки рассылки'
    }

mail_sender/templates/mail_sender/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h2 class="my-0 mr-md-auto font-weight-normal">MAILSENDER v1.0</h2>
      {% if user.is_authenticated %}
          <h5 class="my-0 mr-md-5 font-weight-normal">{{user.email}}</h5>
      {% endif %}
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'mailsender:home' %}">Главная</a>
        {% if user.is_authenticated %}
          <a class="p-2 text-dark" href="{% url 'mailsender:all_customers' %}">Клиенты</a>
          <a class="p-2 text-dark" href="{% url 'mailsender:all_email_templates' %}">Шаблоны писем</a>
          <a class="p-2 text-dark" href="{% url 'mailsender:all_emailing' %}">Рассылки</a>
        {% endif %}
        <a class="p-2 text-dark" href="{% url 'blog:blog' %}">Блог</a>
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'users:logout' %}">Выйти</a>
            <a class="p-2 text-dark" href="{% url 'users:profile' %}">Профиль</a>

        {% else %}
            <a class="p-2 text-dark" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 text-dark" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}

      </nav>
    </div>

    {% block content %}
    {% endblock %}

      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">

            <small class="d-block mb-3 text-muted">&copy; 2023</small>
          </div>
        {% include 'mail_sender/includes/incl_bottom_menu.html' %}
        </div>
      </footer>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

mail_sender/templates/mail_sender/contentemail_confirm_delete.html
{% extends 'mail_sender/base.html' %}
  {% block content %}

        <div class="container">

                <div class="">
                    <form method="post">
                        {% csrf_token %}

                        <h3>Вы уверены что хотите удалить шаблон "{{ object }}"?</h3>
                            <input type="submit" class="btn btn-lg btn-outline-danger" value="Удалить">
                            <a href="{% url 'mailsender:all_email_templates' %}" type="button" class="btn btn-lg btn-outline-warning">Вернуться</a>
                    </form>

                </div>

        </div>

        {% endblock %}

mail_sender/templates/mail_sender/contentemail_detail.html
{% extends 'mail_sender/base.html' %}

  {% block content %}

      <div class="container">

          <div class="card-deck mb-12 text-center">

            <div class="card mb-4 box-shadow">


              <div class="card-body">
                <p>Тема письма: </p>
                <h5 class="">{{ object.headliner }} </h5>
                <p></p>
                <p>Текст письма:</p>
                <h5>{{ object.text }} </h5>
                <p></p>


               <a href="{% url 'mailsender:email_template_update' object.id %}" type="button" class="btn btn-lg btn-outline-warning">Редактировать</a>
               <a href="{% url 'mailsender:all_email_templates' %}" type="button" class="btn btn-lg btn-outline-primary">Вернуться</a>



              </div>

            </div>

          </div>

      </div>
  {% endblock %}

mail_sender/templates/mail_sender/contentemail_form.html
{% extends 'mail_sender/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Добавить шаблон письма</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

mail_sender/templates/mail_sender/contentemail_list.html
{% extends 'mail_sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="">Список шаблонов для рассылки</h1>
      <p class="lead">Тема и текст письма, доступные для рассылок</p>
    </div>


    <div class="container">
        <a href="{% url 'mailsender:email_template_create' %}" class="btn btn-lg btn-outline-primary">Добавить шаблон</a>
        <p></p>
        <div class="row">
            {% for item in object_list%}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">

                            <p class=""><b>Тема письма:</b></p>
                            <p class="">{{ item.headliner }}</p>
                            <p class=""><b>Текст письма:</b></p>
                            <p class="">{{ item.text   | slice:"0:100"}}</p>

                            <div class="row">
                                <div class="col-6">
                                    <a href="{% url 'mailsender:email_template' item.id %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                                </div>

                                <div class="col-6">
                                    <a href="{% url 'mailsender:email_template_delete' item.id %}"><button type="button" class="btn btn-outline-danger" >Удалить</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
  {% endblock %}

mail_sender/templates/mail_sender/customer_confirm_delete.html
{% extends 'mail_sender/base.html' %}
  {% block content %}

        <div class="container">

                <div class="">
                    <form method="post">
                        {% csrf_token %}

                        <h3>Вы уверены что хотите удалить карточку клиента "{{ object }}"?</h3>
                            <input type="submit" class="btn btn-lg btn-outline-danger" value="Удалить">
                            <a href="{% url 'mailsender:all_customers' %}" type="button" class="btn btn-lg btn-outline-warning">Вернуться</a>
                    </form>

                </div>

        </div>

        {% endblock %}

mail_sender/templates/mail_sender/customer_detail.html
{% extends 'mail_sender/base.html' %}

  {% block content %}

      <div class="container">

          <div class="card-deck mb-12 text-center">

            <div class="card mb-4 box-shadow">


              <div class="card-body">
                <p>Имя клиента: </p>
                <h5 class="">{{ object.full_name }} </h5>
                <p></p>
                <p>Электронная почта:</p>
                <h5>{{ object.email }} </h5>
                <p></p>
                <p>Комментарий:</p>
                <h5>{{ object.comment}} </h5>

               <a href="{% url 'mailsender:customer_update' object.id %}" type="button" class="btn btn-lg btn-outline-warning">Редактировать</a>
               <a href="{% url 'mailsender:all_customers' %}" type="button" class="btn btn-lg btn-outline-primary">Вернуться</a>



              </div>

            </div>

          </div>

      </div>
  {% endblock %}

mail_sender/templates/mail_sender/customer_form.html
{% extends 'mail_sender/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Добавить клиента</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

mail_sender/templates/mail_sender/customer_list.html
{% extends 'mail_sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="">Список клиентов для рассылки</h1>
      <p class="lead">Почтовые адреса и имена клиентов, которые подписаны на рассылку</p>
    </div>


    <div class="container">
        <a href="{% url 'mailsender:customer_create' %}" class="btn btn-lg btn-outline-primary">Добавить клиента</a>
        <p></p>
        <div class="row">
            {% for customer in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            {% if customer.full_name %}
                                <p class=""><b>Имя:</b> {{ customer.full_name }}</p>
                            {% else %}
                                <p class=""><b>Имя:</b> не указано</p>
                            {% endif %}
                            <p class=""><b>E-mail:</b> {{ customer.email }} </p>
                            <div class="row">
                                <div class="col-6">
                                    <a href="{% url 'mailsender:customer' customer.id %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                                </div>

                                <div class="col-6">
                                    <a href="{% url 'mailsender:customer_delete' customer.id %}"><button type="button" class="btn btn-outline-danger" >Удалить</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
  {% endblock %}

mail_sender/templates/mail_sender/home.html
{% extends 'mail_sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="">Главная страница</h1>

    </div>


    <div class="container">
        <h3 class="text-center">Статистика текущих почтовых рассылок</h3>
        <div class="row">

            <div class="card-deck mb-3 text-center">
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">Кол-во подписчиков</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="text-center">{{ customers.count }}</h1>
                            <a href="{% url 'mailsender:all_customers' %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-deck mb-3 text-center">
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">Кол-во рассылок</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="text-center">{{ settings.count }}</h1>
                            <a href="{% url 'mailsender:all_emailing' %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-deck mb-3 text-center">
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">Активные рассылки</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="text-center">{{ act_settings.count}}</h1>
                            <a href="{% url 'mailsender:all_emailing' %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                        </div>
                    </div>
                </div>
            </div>

        </div>



        <h3 class="text-center">Статьи в блоге</h3>
        <div class="row">
            {% for post in blog_posts_random%}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal text-center">{{ post.title_name }}</h4>
                        </div>
                        <div class="card-body text-center">
                            <img src='{{post.preview.url }}' align="left" width="100%" height="100%">
                            <p class="text-left">{{ post.content | slice:"0:100" }}</p>
                            <a href="{% url 'blog:blog_article' slug=post.slug %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>




  {% endblock %}

mail_sender/templates/mail_sender/sendsettings_detail.html
{% extends 'mail_sender/base.html' %}

  {% block content %}

      <div class="container">

          <div class="card-deck mb-12 text-center">

            <div class="card mb-4 box-shadow">


              <div class="card-body">
                <p>Название рассылки: </p>
                <h5 class="">{{ object.name }} </h5>
                <p></p>
                <p>Время отправки:</p>
                <h5>{{ object.send_time }} </h5>
                <p></p>
                <p>Статус рассылки:</p>
                <h5>{{ object.get_status_display }} </h5>
                <p></p>
                <p>Периодичность отправки:</p>
                <h5>{{ object.get_period_display }} </h5>
                <p></p>
                <p>Список получателей:</p>
                  {% for customer in object.customer.all %}
                    <h5>{{ customer }} </h5>
                  {% endfor %}
                <p></p>


               <a href="{% url 'mailsender:email_setting_update' object.id %}" type="button" class="btn btn-lg btn-outline-warning">Редактировать</a>
               <a href="{% url 'mailsender:all_emailing' %}" type="button" class="btn btn-lg btn-outline-primary">Вернуться</a>



              </div>

            </div>

          </div>

      </div>
  {% endblock %}

mail_sender/templates/mail_sender/sendsettings_list.html
{% extends 'mail_sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="">Список рассылок</h1>
      <p class="lead">Настройки доступных рассылок</p>
    </div>


    <div class="container">
        <a href="{% url 'mailsender:email_setting_create' %}" class="btn btn-lg btn-outline-primary">Добавить рассылку</a>
        <p></p>
        <div class="row">
            {% for item in object_list%}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">

                            <p class=""><b>Название рассылки:</b></p>
                            <p class="">{{ item.name }}</p>
                            <p class=""><b>Тема письма:</b></p>
                            <p class="">{{ item.message }}</p>
                            <p class=""><b>Статус рассылки:</b></p>
                            <p class="">{{ item.get_status_display }}</p>
                            <p class=""><b>Периодичность рассылки:</b></p>
                            <p class="">{{ item.get_period_display }}</p>

                            <div class="row">
                                <div class="col-6">
                                    <a href="{% url 'mailsender:email_setting' item.id %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                                </div>

                                <div class="col-6">
                                    <a href="{% url 'mailsender:email_setting_delete' item.id %}"><button type="button" class="btn btn-outline-danger" >Удалить</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
  {% endblock %}